# Generated by Django 3.2.6 on 2021-08-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='link_string',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
